// Auto-generated code. Do not edit.
namespace myImages {
    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Kane":return img`
................
......eeeeee....
.....eeeeeeee...
.....eeeeeef....
.....fdddddf....
.....fddfdff....
.....fdddddf....
......fffff.....
......fdddf.....
......fdddf.....
....fffdddff....
...f444fdf44f...
...f4444f444f...
...f44444444f...
...f44444444f...
...f44444444f...
...f44444444f...
...f44444444f...
...f44444444f...
...ffffffffff...
...f66666666f...
...f66666666f...
...f66fffff6f...
...f66f..f66f...
...f66f..f66f...
...f66f..f66f...
...f66f..f66f...
....ff....ff....
................
................
`;
        }
        return null;
    })
    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
        }
        return null;
    })
}
// Auto-generated code. Do not edit.
